# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
    - release/*
    - develop
  tags:
    include:
    - v*

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: prepare
  steps:
  - task: UseGitVersion@5
    displayName: 'GitVersion'
    inputs:
      versionSpec: '5.0.2-beta1.130'
      includePrerelease: true
      updateAssemblyInfo: false
  - script: |
      echo "##vso[build.updatebuildnumber]$(GitVersion.SemVer)"
    displayName: 'Set build version'

- job: build
  dependsOn: prepare
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: pack FubarDev.WebDavServer.sln --output $(Build.ArtifactStagingDirectory) --include-symbols /p:Configuration=$(buildConfiguration) /p:Version=$(build.buildNumber) --verbosity Minimal
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifact: drop

- job: test
  dependsOn: prepare
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'test/FubarDev.WebDavServer.Tests/FubarDev.WebDavServer.Tests.csproj'

- job: publish
  dependsOn:
  - build
  - test
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: drop
      targetPath: $(Build.ArtifactStagingDirectory)
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '3ec8d457-77ef-4e53-b502-600334c12af0/6dd43457-b016-4824-bd52-e44f7757379a'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'webdav-server'
      publishLocation: 'Container'
