# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
    - release/*
    - develop
  tags:
    include:
    - v*

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: prepare
  pool:
    vmImage: 'linux-latest'
  steps:
  - task: UseGitVersion@5
    displayName: 'GitVersion'
    inputs:
      versionSpec: '5.0.2-beta1.130'
      includePrerelease: true
      updateAssemblyInfo: false
  - script: |
      echo "##vso[build.updatebuildnumber]$(GitVersion.SemVer)"
    displayName: 'Set build version'

- job: build
  dependsOn: prepare
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      projects: FubarDev.WebDavServer.sln
      packDirectory: $(Build.ArtifactStagingDirectory)
      includesource: true
      versioningScheme: byBuildNumber
      verbosityPack: Minimal
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifact: drop

- job: test
  dependsOn: prepare
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

- job: publish
  dependsOn: build
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: drop
      targetPath: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'webdav-server'
      publishLocation: 'Container'
