//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 

using System.Xml.Linq;
using System.Xml.Serialization;

namespace FubarDev.WebDavServer.Models {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="DAV:")]
    [XmlRoot(Namespace="DAV:", IsNullable=false)]
    public partial class propfind {
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;

        /// <remarks/>
        [XmlElement("allprop", typeof(object))]
        [XmlElement("include", typeof(include))]
        [XmlElement("prop", typeof(prop))]
        [XmlElement("propname", typeof(object))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="DAV:")]
    public partial class location {
        
        private string hrefField;
        
        /// <remarks/>
        [XmlElement(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="DAV:")]
    public partial class propstat {
        
        private prop propField;
        
        private string statusField;
        
        private error errorField;
        
        private string responsedescriptionField;
        
        private location locationField;
        
        /// <remarks/>
        public prop prop {
            get {
                return this.propField;
            }
            set {
                this.propField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public error error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string responsedescription {
            get {
                return this.responsedescriptionField;
            }
            set {
                this.responsedescriptionField = value;
            }
        }
        
        /// <remarks/>
        public location location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="DAV:")]
    [XmlRoot(Namespace="DAV:", IsNullable=false)]
    public partial class prop {
        
        private XElement[] anyField;

        /// <remarks/>
        [XmlAnyElement()]
        public XElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="DAV:")]
    [XmlRoot(Namespace="DAV:", IsNullable=false)]
    public partial class error {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [XmlAnyElement()]
        [XmlElement("cannot-modify-protected-property", typeof(object))]
        [XmlElement("lock-token-matches-request-uri", typeof(object))]
        [XmlElement("lock-token-submitted", typeof(errorLocktokensubmitted))]
        [XmlElement("no-conflicting-lock", typeof(errorNoconflictinglock))]
        [XmlElement("no-external-entities", typeof(object))]
        [XmlElement("preserved-live-properties", typeof(object))]
        [XmlElement("propfind-finite-depth", typeof(object))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="DAV:")]
    public partial class errorLocktokensubmitted {
        
        private string[] hrefField;
        
        /// <remarks/>
        [XmlElement("href", DataType="anyURI")]
        public string[] href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="DAV:")]
    public partial class errorNoconflictinglock {
        
        private string[] hrefField;
        
        /// <remarks/>
        [XmlElement("href", DataType="anyURI")]
        public string[] href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [XmlType(Namespace="DAV:", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        [XmlEnum("##any:")]
        Item,
        
        /// <remarks/>
        [XmlEnum("cannot-modify-protected-property")]
        cannotmodifyprotectedproperty,
        
        /// <remarks/>
        [XmlEnum("lock-token-matches-request-uri")]
        locktokenmatchesrequesturi,
        
        /// <remarks/>
        [XmlEnum("lock-token-submitted")]
        locktokensubmitted,
        
        /// <remarks/>
        [XmlEnum("no-conflicting-lock")]
        noconflictinglock,
        
        /// <remarks/>
        [XmlEnum("no-external-entities")]
        noexternalentities,
        
        /// <remarks/>
        [XmlEnum("preserved-live-properties")]
        preservedliveproperties,
        
        /// <remarks/>
        [XmlEnum("propfind-finite-depth")]
        propfindfinitedepth,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="DAV:")]
    public partial class include {
        
        private XElement[] anyField;
        
        /// <remarks/>
        [XmlAnyElement()]
        public XElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="DAV:")]
    public partial class lockentry {
        
        private lockscope lockscopeField;
        
        private locktype locktypeField;
        
        /// <remarks/>
        public lockscope lockscope {
            get {
                return this.lockscopeField;
            }
            set {
                this.lockscopeField = value;
            }
        }
        
        /// <remarks/>
        public locktype locktype {
            get {
                return this.locktypeField;
            }
            set {
                this.locktypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="DAV:")]
    public partial class lockscope {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [XmlElement("exclusive", typeof(object))]
        [XmlElement("shared", typeof(object))]
        [XmlChoiceIdentifier("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [XmlType(Namespace="DAV:", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        exclusive,
        
        /// <remarks/>
        shared,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="DAV:")]
    public partial class locktype {
        
        private object itemField;
        
        /// <remarks/>
        [XmlElement("write")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="DAV:")]
    public partial class lockroot {
        
        private string hrefField;
        
        /// <remarks/>
        [XmlElement(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="DAV:")]
    public partial class locktoken {
        
        private string hrefField;
        
        /// <remarks/>
        [XmlElement(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="DAV:")]
    public partial class activelock {
        
        private lockscope lockscopeField;
        
        private locktype locktypeField;
        
        private activelockDepth depthField;
        
        private XElement ownerField;
        
        private string timeoutField;
        
        private locktoken locktokenField;
        
        private lockroot lockrootField;
        
        /// <remarks/>
        public lockscope lockscope {
            get {
                return this.lockscopeField;
            }
            set {
                this.lockscopeField = value;
            }
        }
        
        /// <remarks/>
        public locktype locktype {
            get {
                return this.locktypeField;
            }
            set {
                this.locktypeField = value;
            }
        }
        
        /// <remarks/>
        public activelockDepth depth {
            get {
                return this.depthField;
            }
            set {
                this.depthField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement(Name="owner", Namespace="DAV:")]
        public XElement owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        public string timeout {
            get {
                return this.timeoutField;
            }
            set {
                this.timeoutField = value;
            }
        }
        
        /// <remarks/>
        public locktoken locktoken {
            get {
                return this.locktokenField;
            }
            set {
                this.locktokenField = value;
            }
        }
        
        /// <remarks/>
        public lockroot lockroot {
            get {
                return this.lockrootField;
            }
            set {
                this.lockrootField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [XmlType(AnonymousType=true, Namespace="DAV:")]
    public enum activelockDepth {
        
        /// <remarks/>
        [XmlEnum("0")]
        Item0,
        
        /// <remarks/>
        [XmlEnum("1")]
        Item1,
        
        /// <remarks/>
        infinity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="prop-set", Namespace="DAV:")]
    public partial class propset {
        
        private prop propField;

        /// <remarks/>
        public prop prop {
            get {
                return this.propField;
            }
            set {
                this.propField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="prop-remove", Namespace="DAV:")]
    public partial class propremove {
        
        private prop propField;

        /// <remarks/>
        public prop prop {
            get {
                return this.propField;
            }
            set {
                this.propField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [XmlType(Namespace="DAV:", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        allprop,
        
        /// <remarks/>
        include,
        
        /// <remarks/>
        prop,
        
        /// <remarks/>
        propname,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="DAV:")]
    [XmlRoot(Namespace="DAV:", IsNullable=false)]
    public partial class multistatus {
        
        private response[] responseField;
        
        private string responsedescriptionField;
        
        /// <remarks/>
        [XmlElement("response")]
        public response[] response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public string responsedescription {
            get {
                return this.responsedescriptionField;
            }
            set {
                this.responsedescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="DAV:")]
    [XmlRoot(Namespace="DAV:", IsNullable=false)]
    public partial class response {
        
        private string hrefField;
        
        private object[] itemsField;
        
        private ItemsChoiceType2[] itemsElementNameField;
        
        private error errorField;
        
        private string responsedescriptionField;
        
        /// <remarks/>
        [XmlElement(DataType="anyURI", Order=0)]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("href", typeof(string), DataType="anyURI", Order=1)]
        [XmlElement("propstat", typeof(propstat), Order=1)]
        [XmlElement("status", typeof(string), Order=1)]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ItemsElementName", Order=2)]
        [XmlIgnore()]
        public ItemsChoiceType2[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=3)]
        public error error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=4)]
        public string responsedescription {
            get {
                return this.responsedescriptionField;
            }
            set {
                this.responsedescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [XmlType(Namespace="DAV:", IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
        
        /// <remarks/>
        href,
        
        /// <remarks/>
        propstat,
        
        /// <remarks/>
        status,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="DAV:")]
    [XmlRoot(Namespace="DAV:", IsNullable=false)]
    public partial class propertyupdate {
        
        private object[] itemsField;

        /// <remarks/>
        [XmlElement("remove", typeof(propremove))]
        [XmlElement("set", typeof(propset))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="DAV:")]
    [XmlRoot(Namespace="DAV:", IsNullable=false)]
    public partial class lockinfo {
        
        private lockscope lockscopeField;
        
        private locktype locktypeField;
        
        private XElement ownerField;
        
        /// <remarks/>
        public lockscope lockscope {
            get {
                return this.lockscopeField;
            }
            set {
                this.lockscopeField = value;
            }
        }
        
        /// <remarks/>
        public locktype locktype {
            get {
                return this.locktypeField;
            }
            set {
                this.locktypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement(Name="owner", Namespace="DAV:")]
        public XElement owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="DAV:")]
    [XmlRoot(Namespace="DAV:", IsNullable=false)]
    public partial class supportedlock {
        
        private supportedlockLockentry[] lockentryField;
        
        /// <remarks/>
        [XmlElement("lockentry")]
        public supportedlockLockentry[] lockentry {
            get {
                return this.lockentryField;
            }
            set {
                this.lockentryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="DAV:")]
    public partial class supportedlockLockentry {
        
        private lockscope lockscopeField;
        
        private locktype locktypeField;
        
        /// <remarks/>
        public lockscope lockscope {
            get {
                return this.lockscopeField;
            }
            set {
                this.lockscopeField = value;
            }
        }
        
        /// <remarks/>
        public locktype locktype {
            get {
                return this.locktypeField;
            }
            set {
                this.locktypeField = value;
            }
        }
    }
}
