// <auto-generated />

using System.Xml.Serialization;

namespace FubarDev.WebDavServer.Model
{
    // ReSharper disable once InconsistentNaming
    public partial class prop
    {
        [XmlAttribute("xml:lang", DataType = "language")]
        public string Language { get; set; }
    }
}
